name: Build libhysteria1
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: '1.20.14'
          cache: false
      - name: Build Hysteria 1 client
        run: |
          go version
          git clone --depth 1 --branch v1.3.5 https://github.com/apernet/hysteria.git
          cd hysteria/app
          export CGO_ENABLED=0 GOOS=linux GOARCH=arm64 GOTOOLCHAIN=local
          go build -trimpath -ldflags "-s -w" -o "$GITHUB_WORKSPACE/libhysteria1.so" ./cmd
          ls -la "$GITHUB_WORKSPACE/libhysteria1.so"
      - uses: actions/upload-artifact@v4
        with:
          name: libhysteria1
          path: libhysteria1.so
